import { createContext, useContext } from 'react'

export const languageStorageKey = 'sperm-ai-language'

export const translations = {
  zh: {
    platform: '精蟲 AI 智慧輔助檢驗平台',
    navigation: '快速導覽',
    home: '首頁',
    analysis: '影像分析',
    history: '歷史紀錄',
    settings: '設定',
    openMenu: '開啟導覽選單',
    closeMenu: '關閉導覽選單',
    mainNavigation: '主要導覽',
    systemStatus: '系統狀態',
    normal: '正常',
    cloudModel: '雲端 YOLO 模型',
    offlineReady: '離線備援模式：已準備',
    settingsEyebrow: '偏好設定',
    settingsTitle: '系統設定',
    languageTitle: '語言設定',
    languageDescription: '選擇系統介面要使用的語言。設定會保存在此裝置。',
    saved: '已儲存',
    dashboardEyebrow: '檢驗工作台',
    dashboardTitle: '精蟲檢驗系統',
    newAnalysis: '新增檢驗',
    pendingSamples: '待處理檢體',
    todayWork: '今日工作',
    sampleId: '檢體編號',
    receivedAt: '收件時間',
    status: '狀態',
    action: '操作',
    recentTests: '最近檢驗',
    thisWeek: '本週',
    concentration: '濃度',
    motility: '活動力',
    morphology: '形態',
    interpretation: '判讀',
    view: '查看',
    pending: '待辦',
    analyzing: '進行中',
    attention: '需關注',
    completed: '已完成',
    todayPending: '今日待處理',
    cloudAnalyzing: '雲端辨識中',
    manualReview: '待人工確認',
    todayClosed: '今日已結案',
    startAnalysis: '開始分析',
    reviewResult: '複核結果',
    followUp: '需追蹤',
    uploadSettings: '檢驗設定',
    newTest: '新檢驗',
    basicInfo: '檢體基本資訊',
    patientSampleId: '病患 / 檢體編號',
    spermCount: '精蟲數量與濃度 (YOLO 計數)',
    required: '必選',
    morphologyAssessment: '型態與頭身比評估',
    motilityEstimate: '游動活動力預估 (Motility)',
    toggleMotility: '切換活動力分析',
    imageSource: '影像來源',
    cloudTemplate: '選項 A：從雲端範本選擇',
    cameraUpload: '選項 B：手機拍照 / 相簿上傳',
    chooseImage: '選擇影像',
    openCamera: '開啟相機或從相簿選擇影像',
    videoExtract: '選項 C：短影片抽取',
    videoMode: '影片抽幀分析模式（預留介面）',
    uploadVideo: '上傳 1 秒短片',
    startCloudAnalysis: '開始 AI 雲端分析',
    analysisResult: 'AI 分析結果',
    reanalyze: '重新分析',
    retest: '重新檢測',
    downloadPdf: '下載 PDF',
    downloadReport: '下載報告',
    aiResult: 'AI 判讀結果',
    resultSummary: '本次分析顯示精子濃度偏低，建議由專業人員確認並安排後續追蹤檢測。',
    spermCountLabel: '精蟲數量',
    whoPass: '綠色：達標 WHO 標準',
    headBodyRatio: '型態與頭身比',
    normalMorphology: '正常型態',
    lowFollowUp: '偏低，建議追蹤',
    motilityEstimateLabel: '活動力預估',
    progressive: '前進性',
    moderateMotility: '活動力中等',
    imageYolo: '影像與 YOLO 標註',
    originalImage: '原始顯微影像',
    yoloView: 'AI YOLO 標註視圖',
    detected: '辨識成功',
    precision: 'Precision',
    confidence: 'Confidence',
    testSummary: '檢驗摘要',
    medicalBenefit: '醫管效益',
    benefitText: '本分析耗時 1.2 秒，已為醫檢師省下人工計數時間與判讀重複性差異。',
    testInfo: '檢驗資訊',
    patientCode: '病患代號',
    testItems: '檢驗項目',
    collectionTime: '採集時間',
    saveToHistory: '儲存至病患歷程',
    historyList: '檢驗紀錄列表',
    historySearchPlaceholder: '搜尋病患 / 檢驗編號 / 日期 / 處理狀態',
    noRecords: '查無符合條件的紀錄',
    viewDetails: '查看詳情',
    previousPage: '上一頁',
    patientData: '病患資料',
    patientNumber: '病患編號',
    sex: '性別',
    age: '年齡',
    phone: '電話',
    doctor: '主治醫師',
    processingStatus: '處理狀態',
    aiInterpretation: 'AI 判讀資訊',
    processingTime: '處理時間',
    notes: '病歷與備註',
    trend: '精子數量趨勢',
    loadingTitle: 'AI 雲端分析中',
    loadingDescription: '影像上傳中 • YOLO 辨識中 • 形態評估中',
    templateA: '範例檢體 A - 高濃度正常',
    templateB: '範例檢體 B - 型態異常案例',
    templateC: '範例檢體 C - 低濃度待追蹤',
    loginEyebrow: '安全登入',
    loginTitle: '登入系統',
    loginDescription: '請輸入帳號與密碼以使用精蟲 AI 檢驗平台。',
    username: '帳號',
    password: '密碼',
    usernamePlaceholder: '請輸入帳號',
    passwordPlaceholder: '請輸入密碼',
    invalidCredentials: '帳號或密碼錯誤，請重新確認。',
    login: '登入',
    logout: '登出',
  },
  en: {
    platform: 'Sperm AI Assisted Analysis Platform',
    navigation: 'Quick navigation',
    home: 'Home',
    analysis: 'Analysis',
    history: 'History',
    settings: 'Settings',
    openMenu: 'Open navigation menu',
    closeMenu: 'Close navigation menu',
    mainNavigation: 'Main navigation',
    systemStatus: 'System status',
    normal: 'Normal',
    cloudModel: 'Cloud YOLO model',
    offlineReady: 'Offline fallback: ready',
    settingsEyebrow: 'Preferences',
    settingsTitle: 'System settings',
    languageTitle: 'Language',
    languageDescription: 'Choose the interface language. Your choice is saved on this device.',
    saved: 'Saved',
    dashboardEyebrow: 'Analysis workspace', dashboardTitle: 'Sperm analysis system', newAnalysis: 'New analysis',
    pendingSamples: 'Pending samples', todayWork: "Today's work", sampleId: 'Sample ID', receivedAt: 'Received', status: 'Status', action: 'Action',
    recentTests: 'Recent tests', thisWeek: 'This week', concentration: 'Concentration', motility: 'Motility', morphology: 'Morphology', interpretation: 'Interpretation', view: 'View',
    pending: 'To do', analyzing: 'In progress', attention: 'Attention', completed: 'Completed', todayPending: 'Pending today', cloudAnalyzing: 'Cloud analysis', manualReview: 'Manual review', todayClosed: 'Closed today',
    startAnalysis: 'Start analysis', reviewResult: 'Review result', followUp: 'Follow-up', uploadSettings: 'Test setup', newTest: 'New test', basicInfo: 'Sample information', patientSampleId: 'Patient / sample ID', spermCount: 'Sperm count and concentration (YOLO)', required: 'Required', morphologyAssessment: 'Morphology and head-body assessment', motilityEstimate: 'Motility estimate', toggleMotility: 'Toggle motility analysis', imageSource: 'Image source', cloudTemplate: 'Option A: Cloud template', cameraUpload: 'Option B: Camera / photo library', chooseImage: 'Choose image', openCamera: 'Open camera or choose an image', videoExtract: 'Option C: Video extraction', videoMode: 'Video frame analysis (reserved)', uploadVideo: 'Upload 1-second clip', startCloudAnalysis: 'Start AI cloud analysis',
    analysisResult: 'AI analysis result', reanalyze: 'Reanalyze', retest: 'Retest', downloadPdf: 'Download PDF', downloadReport: 'Download report', aiResult: 'AI interpretation', resultSummary: 'The analysis shows low sperm concentration. Professional review and follow-up testing are recommended.', spermCountLabel: 'Sperm count', whoPass: 'Green: meets WHO standard', headBodyRatio: 'Morphology and head-body ratio', normalMorphology: 'Normal morphology', lowFollowUp: 'Low, follow-up recommended', motilityEstimateLabel: 'Motility estimate', progressive: 'Progressive', moderateMotility: 'Moderate motility', imageYolo: 'Image and YOLO annotation', originalImage: 'Original microscope image', yoloView: 'AI YOLO annotation view', detected: 'Detected', precision: 'Precision', confidence: 'Confidence', testSummary: 'Test summary', medicalBenefit: 'Clinical benefit', benefitText: 'This analysis took 1.2 seconds, reducing manual counting time and interpretation variation for laboratory staff.', testInfo: 'Test information', patientCode: 'Patient code', testItems: 'Test items', collectionTime: 'Collection time', saveToHistory: 'Save to patient history', historyList: 'Test history', historySearchPlaceholder: 'Search patient / sample ID / date / status', noRecords: 'No matching records', viewDetails: 'View details', previousPage: 'Back', patientData: 'Patient data', patientNumber: 'Patient number', sex: 'Sex', age: 'Age', phone: 'Phone', doctor: 'Doctor', processingStatus: 'Processing status', aiInterpretation: 'AI interpretation', processingTime: 'Processing time', notes: 'Medical notes', trend: 'Sperm count trend', loadingTitle: 'AI cloud analysis in progress', loadingDescription: 'Uploading image • YOLO detection • Morphology assessment',
    templateA: 'Sample A - High concentration', templateB: 'Sample B - Abnormal morphology', templateC: 'Sample C - Low concentration',
    loginEyebrow: 'Secure sign in', loginTitle: 'Sign in', loginDescription: 'Enter your username and password to use the Sperm AI analysis platform.', username: 'Username', password: 'Password', usernamePlaceholder: 'Enter username', passwordPlaceholder: 'Enter password', invalidCredentials: 'Incorrect username or password. Please try again.', login: 'Sign in', logout: 'Sign out',
  },
  ko: {
    platform: '정자 AI 보조 분석 플랫폼',
    navigation: '빠른 탐색',
    home: '홈',
    analysis: '분석',
    history: '기록',
    settings: '설정',
    openMenu: '탐색 메뉴 열기',
    closeMenu: '탐색 메뉴 닫기',
    mainNavigation: '주요 탐색', systemStatus: '시스템 상태', normal: '정상', cloudModel: '클라우드 YOLO 모델', offlineReady: '오프라인 백업: 준비됨',
    settingsEyebrow: '환경 설정',
    settingsTitle: '시스템 설정',
    languageTitle: '언어 설정',
    languageDescription: '사용할 인터페이스 언어를 선택하세요. 이 설정은 기기에 저장됩니다.',
    saved: '저장됨',
    dashboardEyebrow: '검사 작업대', dashboardTitle: '정자 검사 시스템', newAnalysis: '새 검사', pendingSamples: '처리 대기 검체', todayWork: '오늘의 작업', sampleId: '검체 번호', receivedAt: '접수 시간', status: '상태', action: '작업', recentTests: '최근 검사', thisWeek: '이번 주', concentration: '농도', motility: '운동성', morphology: '형태', interpretation: '판독', view: '보기', pending: '대기', analyzing: '진행 중', attention: '주의 필요', completed: '완료', todayPending: '오늘 처리 대기', cloudAnalyzing: '클라우드 분석 중', manualReview: '수동 확인 대기', todayClosed: '오늘 완료', startAnalysis: '분석 시작', reviewResult: '결과 검토', followUp: '추적 관찰', uploadSettings: '검사 설정', newTest: '새 검사', basicInfo: '검체 기본 정보', patientSampleId: '환자 / 검체 번호', spermCount: '정자 수와 농도 (YOLO 계수)', required: '필수', morphologyAssessment: '형태 및 머리-몸통 평가', motilityEstimate: '운동성 예측', toggleMotility: '운동성 분석 전환', imageSource: '이미지 출처', cloudTemplate: '옵션 A: 클라우드 템플릿', cameraUpload: '옵션 B: 카메라 / 앨범 업로드', chooseImage: '이미지 선택', openCamera: '카메라를 열거나 앨범에서 이미지 선택', videoExtract: '옵션 C: 짧은 영상 추출', videoMode: '영상 프레임 분석 모드 (준비 중)', uploadVideo: '1초 영상 업로드', startCloudAnalysis: 'AI 클라우드 분석 시작', analysisResult: 'AI 분석 결과', reanalyze: '다시 분석', retest: '재검사', downloadPdf: 'PDF 다운로드', downloadReport: '보고서 다운로드', aiResult: 'AI 판독 결과', resultSummary: '분석 결과 정자 농도가 낮습니다. 전문가 확인과 후속 검사를 권장합니다.', spermCountLabel: '정자 수', whoPass: '녹색: WHO 기준 충족', headBodyRatio: '형태 및 머리-몸통 비율', normalMorphology: '정상 형태', lowFollowUp: '낮음, 추적 관찰 권장', motilityEstimateLabel: '운동성 예측', progressive: '전진성', moderateMotility: '운동성 보통', imageYolo: '이미지 및 YOLO 표시', originalImage: '원본 현미경 이미지', yoloView: 'AI YOLO 표시 보기', detected: '검출 성공', precision: 'Precision', confidence: 'Confidence', testSummary: '검사 요약', medicalBenefit: '임상 효과', benefitText: '분석에 1.2초가 걸려 검사자의 수동 계수 시간과 판독 편차를 줄였습니다.', testInfo: '검사 정보', patientCode: '환자 코드', testItems: '검사 항목', collectionTime: '채취 시간', saveToHistory: '환자 기록에 저장', historyList: '검사 기록 목록', historySearchPlaceholder: '환자 / 검체 번호 / 날짜 / 상태 검색', noRecords: '조건에 맞는 기록이 없습니다', viewDetails: '상세 보기', previousPage: '이전 페이지', patientData: '환자 정보', patientNumber: '환자 번호', sex: '성별', age: '나이', phone: '전화', doctor: '담당 의사', processingStatus: '처리 상태', aiInterpretation: 'AI 판독 정보', processingTime: '처리 시간', notes: '진료 기록 및 메모', trend: '정자 수 추이', loadingTitle: 'AI 클라우드 분석 중', loadingDescription: '이미지 업로드 • YOLO 검출 • 형태 평가',
    templateA: '샘플 A - 고농도 정상', templateB: '샘플 B - 형태 이상 사례', templateC: '샘플 C - 저농도 추적 관찰',
    loginEyebrow: '보안 로그인', loginTitle: '로그인', loginDescription: '정자 AI 검사 플랫폼을 사용하려면 아이디와 비밀번호를 입력하세요.', username: '아이디', password: '비밀번호', usernamePlaceholder: '아이디 입력', passwordPlaceholder: '비밀번호 입력', invalidCredentials: '아이디 또는 비밀번호가 올바르지 않습니다. 다시 시도하세요.', login: '로그인', logout: '로그아웃',
  },
}

export const LanguageContext = createContext(null)

export function useLanguage() {
  return useContext(LanguageContext)
}

export const languageOptions = [
  { value: 'zh', label: '繁體中文' },
  { value: 'en', label: 'English' },
  { value: 'ko', label: '한국어' },
]
