import { createContext, useContext } from 'react'

export const languageStorageKey = 'sperm-ai-language'

export const translations = {
  zh: {
    platform: '精蟲 AI 智慧輔助檢驗平台',
    navigation: '快速導覽',
    home: '首頁',
    analysis: '影像分析',
    history: '歷史紀錄',
    settings: '設定',
    openMenu: '開啟導覽選單',
    closeMenu: '關閉導覽選單',
    mainNavigation: '主要導覽',
    systemStatus: '系統狀態',
    normal: '正常',
    cloudModel: '雲端 YOLO 模型',
    offlineReady: '離線備援模式：已準備',
    settingsEyebrow: '偏好設定',
    settingsTitle: '系統設定',
    languageTitle: '語言設定',
    languageDescription: '選擇系統介面要使用的語言。設定會保存在此裝置。',
    saved: '已儲存',
    healthCardTitle: '健保卡讀卡服務',
    healthCardDescription: '電腦使用讀卡機時，請先安裝並啟動本機讀卡服務。iPad 與手機請改用手動輸入。',
    healthCardComputerOnly: '電腦使用',
    healthCardVersionLabel: 'v0.3.0',
    healthCardSupportedVersion: '目前支援版本',
    healthCardLocalAddress: '本機服務位址',
    healthCardCurrentOrigin: '目前網站 Origin',
    healthCardPlatformLabel: '平台指南',
    healthCardPlatformMacos: 'macOS',
    healthCardPlatformWindows: 'Windows',
    healthCardPlatformMobile: 'iPad／行動裝置',
    healthCardMacTitle: 'macOS 使用指南（自行編譯）',
    healthCardMacPrerequisites: '需要 macOS、網路、Git、Rust／Cargo、PC/SC 相容晶片讀卡機與對應驅動程式。',
    healthCardMacStepOne: '步驟一：確認 Rust',
    healthCardMacStepOneHint: '若找不到 cargo，請依下方提示安裝 Rust，然後重新開啟 Terminal。',
    healthCardMacStepTwo: '步驟二：下載 v0.3.0',
    healthCardMacStepTwoHint: '固定使用版本化資料夾；若資料夾已存在，請進入資料夾後執行 git fetch --tags && git checkout v0.3.0，不要刪除資料夾。detached HEAD 是正常的。',
    healthCardMacStepThree: '步驟三：編譯',
    healthCardMacStepThreeHint: '首次編譯會下載套件，成功時會看到 Finished release profile。',
    healthCardMacStepFour: '步驟四：啟動服務',
    healthCardMacStepFourHint: 'Terminal 必須保持開啟；關閉 Terminal 或按 Control + C 後服務會停止。成功時應看到 listening on http://127.0.0.1:12345。',
    healthCardVerifyVersion: '開啟 /version 驗證版本',
    healthCardVerifySnapshot: '開啟 / 驗證讀卡狀態',
    healthCardTroubleshooting: 'macOS 常見問題',
    healthCardTroubleshootingItems: [
      { title: 'cargo: command not found：', text: '尚未安裝 Rust，或安裝後尚未重新開啟 Terminal。安裝指令：curl --proto \'=https\' --tlsv1.2 -sSf https://sh.rustup.rs | sh' },
      { title: 'destination path already exists：', text: '資料夾已存在，直接進入資料夾並 checkout v0.3.0，不要重新 clone。' },
      { title: '/version 可以開啟但網站無法連線：', text: '通常是啟動服務時沒有加入目前網站 Origin，請重新複製上方指令；瀏覽器若詢問本機網路權限請允許。' },
      { title: 'pcsc_unavailable：', text: '檢查讀卡機驅動程式與 USB 連線，拔除讀卡機後重新連接。' },
      { title: 'SharingViolation：', text: '關閉其他正在使用健保卡或讀卡機的程式。' },
      { title: 'Chrome 與 Safari 結果不同：', text: '分別確認瀏覽器的本機網路權限，重新整理後再次檢查。' },
    ],
    healthCardWindowsTitle: 'Windows 使用指南（v0.3.0 x64）',
    healthCardWindowsStepOne: '安裝晶片讀卡機驅動程式。',
    healthCardWindowsStepTwo: '下載官方 v0.3.0 x64 讀卡程式。',
    healthCardWindowsStepThree: '雙擊執行 .exe。',
    healthCardWindowsStepFour: '保持讀卡程式視窗開啟。',
    healthCardWindowsStepFive: '接上讀卡機並插入健保卡。',
    healthCardWindowsStepSix: '回到設定頁按「檢查讀卡服務」。',
    healthCardWindowsWarning: '讀卡程式視窗關閉後，讀卡功能就會停止。',
    healthCardWindowsNote: '目前是測試／初期使用方式，不是完整 Windows installer。自動啟動、程式簽章與固定網站來源列為後續優化；若已安裝舊版 v0.2.3，請先關閉舊版再啟動 v0.3.0。',
    healthCardMobileTitle: 'iPad、iPhone 與行動裝置',
    healthCardMobileDescription: '目前無法直接執行桌面版讀卡服務，也無法透過一般 Safari／行動瀏覽器操作 USB 健保卡讀卡機，請使用手動輸入病人資料。',
    healthCardManualInput: '改用手動輸入',
    healthCardCopy: '複製指令',
    healthCardCopied: '已複製',
    healthCardStatusChecking: '檢查中…',
    healthCardStatusNotChecked: '尚未檢查',
    healthCardStatusReady: '正常',
    healthCardStatusConnection: '無法連線本機讀卡服務，請確認程式是否正在執行',
    healthCardStatusOldVersion: '偵測到舊版，請更新讀卡程式',
    healthCardStatusPcscUnavailable: '智慧卡服務尚未啟動或無法使用',
    healthCardStatusNoReader: '找不到讀卡機',
    healthCardStatusEmpty: '讀卡機已連線，請插入健保卡',
    healthCardStatusCardReady: '已成功讀取健保卡',
    healthCardStatusUnsupported: '插入的卡片不是健保卡',
    healthCardStatusSharingViolation: '卡片正在被其他程式使用，請關閉其他讀卡程式後重試',
    healthCardStatusNoCard: '尚未讀到健保卡',
    healthCardStatusUnavailable: '未就緒',
    healthCardPrivacy: '隱私提醒：健保卡包含個人資料。請勿分享 / 的完整結果或在客服訊息貼上姓名、身分證字號、生日、卡號；錯誤回報不得包含完整健保卡資料。',
    healthCardService: '讀卡服務',
    healthCardProgramVersion: '程式版本',
    healthCardPcscLabel: '電腦智慧卡服務',
    healthCardRecheck: '重新檢查',
    healthCardStatusUnknown: '狀態未知',
    healthCardStatusReaderConnected: '已連線',
    healthCardStatusReaderError: '讀卡機錯誤',
    healthCardCopyError: '無法複製，請手動選取指令',
    healthCardCommandLabel: '指令',
    healthCardRustInstallLabel: 'Rust 安裝指令',
    healthCardDownloadLabel: '下載 v0.3.0',
    healthCardExistingFolderLabel: '資料夾已存在時',
    healthCardBuildLabel: '編譯指令',
    healthCardLocalLabel: '本機開發測試',
    healthCardPreviewLabel: '目前預覽環境',
    healthCardProductionLabel: '正式網站使用',
    healthCardAdvanced: '進階資訊與疑難排解',
    healthCardDownload: '下載 TW NHI IC Card Service',
    healthCardDownloadDescription: '開啟官方 v0.3.0 Releases 與各平台下載檔案',
    healthCardWindowsDownload: '下載 Windows 64 位元讀卡程式',
    healthCardWindowsDownloadDescription: '官方 v0.3.0 x64 .exe；目前不需要 installer',
    healthCardStepsTitle: '其他電腦安裝後的使用步驟',
    healthCardStepOne: '安裝讀卡機驅動程式，並將讀卡機連接到電腦。',
    healthCardStepTwo: 'macOS 請從 v0.3.0 原始碼編譯；Windows 請下載官方 v0.3.0 x64 執行檔。',
    healthCardStepThree: '插入健保卡，開啟終端機或命令提示字元。',
    healthCardStepFour: '依作業系統執行下方對應的讀卡服務檔案，並保持該視窗開啟。',
    healthCardStepFive: '回到本系統網站登入，進入新增檢驗後按「讀取健保卡」。',
    healthCardStartCommand: '依作業系統啟動（v0.3.0）',
    healthCardMac: 'macOS：編譯後從 Terminal 啟動',
    healthCardWindows: 'Windows 64 位元：下載後雙擊啟動',
    healthCardLinux: 'Linux x86_64：下載後',
    healthCardNote: '目前使用 http://127.0.0.1:12345。Windows 讀卡程式視窗關閉後，讀卡功能會停止。Windows installer、自動啟動、程式簽章與固定 allow-origin 列為後續正式產品優化。',
    healthCardCheckTitle: '檢查讀卡服務',
    healthCardCheckDescription: '依序檢查 /version、PC/SC、讀卡機與健保卡狀態。',
    healthCardBrowserNote: '建議使用 Google Chrome。第一次從正式網站使用讀卡功能時，請允許瀏覽器存取本機網路。若拒絕權限，可在 Chrome 的「網站設定 → 本機網路存取」改成允許，重新整理頁面後再次檢查。Safari 暫時可能受瀏覽器安全限制；若無法連線，請改用 Chrome 或手動輸入。',
    healthCardCheckButton: '檢查讀卡服務',
    healthCardChecking: '檢查中…',
    healthCardVersion: '服務版本',
    healthCardPcsc: 'PC/SC',
    healthCardReader: '讀卡機',
    healthCardCard: '健保卡',
    healthCardReady: '正常',
    healthCardUnavailable: '未就緒',
    healthCardMacCommandTitle: 'macOS 開發啟動（正式網站來源）',
    dashboardEyebrow: '檢驗工作台',
    dashboardTitle: '精蟲檢驗系統',
    newAnalysis: '新增檢驗',
    pendingSamples: '待處理檢體',
    todayWork: '今日工作',
    sampleId: '檢體編號',
    receivedAt: '收件時間',
    status: '狀態',
    action: '操作',
    recentTests: '最近檢驗',
    thisWeek: '本週',
    concentration: '濃度',
    motility: '活動力',
    morphology: '形態',
    interpretation: '判讀',
    view: '查看',
    pending: '待辦',
    analyzing: '進行中',
    attention: '需關注',
    completed: '已完成',
    todayPending: '今日待處理',
    cloudAnalyzing: '雲端辨識中',
    manualReview: '待人工確認',
    todayClosed: '今日已結案',
    startAnalysis: '開始分析',
    reviewResult: '複核結果',
    followUp: '需追蹤',
    uploadSettings: '檢驗設定',
    newTest: '新檢驗',
    basicInfo: '檢體基本資訊',
    patientSampleId: '病患 / 檢體編號',
    spermCount: '精蟲數量與濃度 (YOLO 計數)',
    required: '必選',
    morphologyAssessment: '型態與頭身比評估',
    motilityEstimate: '游動活動力預估 (Motility)',
    toggleMotility: '切換活動力分析',
    imageSource: '影像來源',
    cloudTemplate: '選項 A：從雲端範本選擇',
    cameraUpload: '選項 B：手機拍照 / 相簿上傳',
    chooseImage: '選擇影像',
    openCamera: '開啟相機或從相簿選擇影像',
    videoExtract: '選項 C：短影片抽取',
    videoMode: '影片抽幀分析模式（預留介面）',
    uploadVideo: '上傳 1 秒短片',
    startCloudAnalysis: '開始 AI 雲端分析',
    analysisResult: 'AI 分析結果',
    reanalyze: '重新分析',
    retest: '重新檢測',
    downloadPdf: '下載 PDF',
    downloadReport: '下載報告',
    aiResult: 'AI 判讀結果',
    resultSummary: '本次分析顯示精子濃度偏低，建議由專業人員確認並安排後續追蹤檢測。',
    spermCountLabel: '精蟲數量',
    whoPass: '綠色：達標 WHO 標準',
    headBodyRatio: '型態與頭身比',
    normalMorphology: '正常型態',
    lowFollowUp: '偏低，建議追蹤',
    motilityEstimateLabel: '活動力預估',
    progressive: '前進性',
    moderateMotility: '活動力中等',
    imageYolo: '影像與 YOLO 標註',
    originalImage: '原始顯微影像',
    yoloView: 'AI YOLO 標註視圖',
    detected: '辨識成功',
    precision: 'Precision',
    confidence: 'Confidence',
    testSummary: '檢驗摘要',
    medicalBenefit: '醫管效益',
    benefitText: '本分析耗時 1.2 秒，已為醫檢師省下人工計數時間與判讀重複性差異。',
    testInfo: '檢驗資訊',
    patientCode: '病患代號',
    testItems: '檢驗項目',
    collectionTime: '採集時間',
    saveToHistory: '儲存至病患歷程',
    historyList: '檢驗紀錄列表',
    historySearchPlaceholder: '搜尋病患 / 檢驗編號 / 日期 / 處理狀態',
    noRecords: '查無符合條件的紀錄',
    viewDetails: '查看詳情',
    previousPage: '上一頁',
    patientData: '病患資料',
    patientName: '病患姓名',
    patientId: '病患 ID',
    patientCount: '位病患',
    recordCount: '筆檢測',
    latestRecord: '最近檢測',
    viewPatientHistory: '查看病患歷史',
    patientHistory: '病患歷史',
    patientRecords: '歷次檢測紀錄',
    patientNumber: '病患編號',
    sex: '性別',
    age: '年齡',
    phone: '電話',
    doctor: '主治醫師',
    processingStatus: '處理狀態',
    aiInterpretation: 'AI 判讀資訊',
    processingTime: '處理時間',
    notes: '病歷與備註',
    trend: '精子數量趨勢',
    trendChartTitle: '歷史趨勢折線圖',
    trendChartDescription: '查看同一位病患不同檢測日期的分析數值變化。',
    trendMetric: '比較指標',
    trendDate: '檢測日期',
    trendValue: '數值',
    loadingTitle: 'AI 雲端分析中',
    loadingDescription: '影像上傳中 • YOLO 辨識中 • 形態評估中',
    templateA: '範例檢體 A - 高濃度正常',
    templateB: '範例檢體 B - 型態異常案例',
    templateC: '範例檢體 C - 低濃度待追蹤',
    loginEyebrow: '安全登入',
    loginTitle: '登入系統',
    loginDescription: '請輸入帳號與密碼以使用精蟲 AI 檢驗平台。',
    username: '帳號',
    password: '密碼',
    usernamePlaceholder: '請輸入帳號',
    passwordPlaceholder: '請輸入密碼',
    invalidCredentials: '帳號或密碼錯誤，請重新確認。',
    login: '登入',
    logout: '登出',
    filter: '篩選',
    startDate: '開始日期',
    endDate: '結束日期',
    clearFilters: '清除篩選',
    resultCount: '筆紀錄',
    averageResults: '歷次平均結果',
    averageConcentration: '平均濃度',
    averageMotility: '平均活動力',
    averageMorphology: '平均正常型態',
    doctorComment: '醫師評語',
    doctorCommentPlaceholder: '請輸入醫師評語或追蹤建議',
    saveComment: '儲存評語',
    commentSaved: '評語已儲存',
    expandRecord: '展開檢測詳情',
    collapseRecord: '收合檢測詳情',
  },
  en: {
    platform: 'Sperm AI Assisted Analysis Platform',
    navigation: 'Quick navigation',
    home: 'Home',
    analysis: 'Analysis',
    history: 'History',
    settings: 'Settings',
    openMenu: 'Open navigation menu',
    closeMenu: 'Close navigation menu',
    mainNavigation: 'Main navigation',
    systemStatus: 'System status',
    normal: 'Normal',
    cloudModel: 'Cloud YOLO model',
    offlineReady: 'Offline fallback: ready',
    settingsEyebrow: 'Preferences',
    settingsTitle: 'System settings',
    languageTitle: 'Language',
    languageDescription: 'Choose the interface language. Your choice is saved on this device.',
    saved: 'Saved',
    healthCardTitle: 'Health card reader service',
    healthCardStatusReady: 'Ready',
    healthCardDescription: 'Install and start the local reader service before using a card reader on a computer. Use manual entry on iPad and phones.',
    healthCardComputerOnly: 'Computer only',
    healthCardVersionLabel: 'v0.3.0', healthCardProgramVersion: 'Program version', healthCardSupportedVersion: 'Supported version', healthCardLocalAddress: 'Local service', healthCardCurrentOrigin: 'Current website Origin', healthCardPlatformLabel: 'Platform guide', healthCardPlatformMacos: 'macOS', healthCardPlatformWindows: 'Windows', healthCardPlatformMobile: 'iPad / mobile',
    healthCardWindowsTitle: 'Windows guide (v0.3.0 x64)', healthCardWindowsStepOne: 'Install the smart-card reader driver.', healthCardWindowsStepTwo: 'Download the official v0.3.0 x64 reader.', healthCardWindowsStepThree: 'Double-click the .exe.', healthCardWindowsStepFour: 'Keep the reader window open.', healthCardWindowsStepFive: 'Connect the reader and insert the NHI card.', healthCardWindowsStepSix: 'Return to Settings and select Check reader service.', healthCardWindowsWarning: 'Card reading stops when the reader program window is closed.', healthCardWindowsNote: 'This is the test/initial workflow, not a complete Windows installer. Auto-start, signing, and fixed website origin are future improvements. Close v0.2.3 before starting v0.3.0.', healthCardMobileTitle: 'iPad, iPhone, and mobile devices', healthCardMobileDescription: 'Desktop reader services cannot currently run directly on mobile devices, and normal Safari/mobile browsers cannot operate a USB NHI reader. Use manual patient entry.', healthCardManualInput: 'Use manual entry', healthCardCopy: 'Copy command', healthCardCopied: 'Copied', healthCardStatusChecking: 'Checking…', healthCardStatusConnection: 'Cannot connect to the local reader service. Confirm that it is running.', healthCardStatusOldVersion: 'An old version was detected. Update the reader.', healthCardStatusPcscUnavailable: 'The smart-card service is unavailable.', healthCardStatusNoReader: 'No reader found.', healthCardStatusEmpty: 'Reader connected. Insert an NHI card.', healthCardStatusCardReady: 'NHI card read successfully.', healthCardStatusUnsupported: 'The inserted card is not an NHI card.', healthCardStatusSharingViolation: 'The card is in use by another program. Close other reader programs and retry.', healthCardStatusNoCard: 'No NHI card detected.', healthCardStatusUnavailable: 'Not ready.', healthCardPrivacy: 'Privacy reminder: NHI cards contain personal data. Do not share the full / response or send names, IDs, birthdays, or card numbers in support messages.',
    healthCardService: 'Reader service', healthCardPcscLabel: 'Computer smart-card service', healthCardRecheck: 'Check again', healthCardStatusUnknown: 'Unknown status', healthCardStatusReaderConnected: 'Connected', healthCardStatusReaderError: 'Reader error', healthCardCopyError: 'Unable to copy. Select the command manually.', healthCardCommandLabel: 'Command', healthCardRustInstallLabel: 'Rust installation command', healthCardDownloadLabel: 'Download v0.3.0', healthCardExistingFolderLabel: 'If the folder already exists', healthCardBuildLabel: 'Build command', healthCardLocalLabel: 'Local development', healthCardPreviewLabel: 'Current preview environment', healthCardProductionLabel: 'Production website', healthCardAdvanced: 'Advanced information and troubleshooting',
    healthCardDownload: 'Download TW NHI IC Card Service',
    healthCardDownloadDescription: 'Open official v0.3.0 Releases and platform downloads',
    healthCardWindowsDownload: 'Download Windows 64-bit reader',
    healthCardWindowsDownloadDescription: 'Official v0.3.0 x64 .exe; no installer required for now',
    healthCardStepsTitle: 'Steps for another computer',
    healthCardStepOne: 'Install the card reader driver and connect the reader to the computer.',
    healthCardStepTwo: 'On macOS, build v0.3.0 from source; on Windows, download the official v0.3.0 x64 executable.',
    healthCardStepThree: 'Insert the NHI card and open Terminal or Command Prompt.',
    healthCardStepFour: 'Run the matching reader service below and keep the window open.',
    healthCardStepFive: 'Return to this website, sign in, open a new analysis, and select Read health card.',
    healthCardStartCommand: 'Start by operating system (v0.3.0)',
    healthCardMac: 'macOS: start from Terminal after building',
    healthCardWindows: 'Windows 64-bit: double-click after download',
    healthCardLinux: 'Linux x86_64: after download',
    healthCardNote: 'The service uses http://127.0.0.1:12345. Windows card reading stops when the reader window is closed. Installer, auto-start, signing, and fixed allow-origin are future product improvements.',
    healthCardCheckTitle: 'Check reader service',
    healthCardCheckDescription: 'Check /version, PC/SC, the reader, and the NHI card in order.',
    healthCardBrowserNote: 'Google Chrome is recommended. The first time you use card reading from the production website, allow the browser to access the local network. If permission was denied, change Chrome Settings → Local network access to Allow, reload the page, and check again. Safari may be limited by browser security; use Chrome or manual entry if it cannot connect.',
    healthCardCheckButton: 'Check reader service',
    healthCardChecking: 'Checking…',
    healthCardVersion: 'Service version',
    healthCardPcsc: 'PC/SC',
    healthCardReader: 'Reader',
    healthCardCard: 'NHI card',
    healthCardReady: 'Ready',
    healthCardUnavailable: 'Not ready',
    healthCardMacCommandTitle: 'macOS development start (production website origin)',
    dashboardEyebrow: 'Analysis workspace', dashboardTitle: 'Sperm analysis system', newAnalysis: 'New analysis',
    pendingSamples: 'Pending samples', todayWork: "Today's work", sampleId: 'Sample ID', receivedAt: 'Received', status: 'Status', action: 'Action',
    recentTests: 'Recent tests', thisWeek: 'This week', concentration: 'Concentration', motility: 'Motility', morphology: 'Morphology', interpretation: 'Interpretation', view: 'View',
    pending: 'To do', analyzing: 'In progress', attention: 'Attention', completed: 'Completed', todayPending: 'Pending today', cloudAnalyzing: 'Cloud analysis', manualReview: 'Manual review', todayClosed: 'Closed today',
    startAnalysis: 'Start analysis', reviewResult: 'Review result', followUp: 'Follow-up', uploadSettings: 'Test setup', newTest: 'New test', basicInfo: 'Sample information', patientSampleId: 'Patient / sample ID', spermCount: 'Sperm count and concentration (YOLO)', required: 'Required', morphologyAssessment: 'Morphology and head-body assessment', motilityEstimate: 'Motility estimate', toggleMotility: 'Toggle motility analysis', imageSource: 'Image source', cloudTemplate: 'Option A: Cloud template', cameraUpload: 'Option B: Camera / photo library', chooseImage: 'Choose image', openCamera: 'Open camera or choose an image', videoExtract: 'Option C: Video extraction', videoMode: 'Video frame analysis (reserved)', uploadVideo: 'Upload 1-second clip', startCloudAnalysis: 'Start AI cloud analysis',
    analysisResult: 'AI analysis result', reanalyze: 'Reanalyze', retest: 'Retest', downloadPdf: 'Download PDF', downloadReport: 'Download report', aiResult: 'AI interpretation', resultSummary: 'The analysis shows low sperm concentration. Professional review and follow-up testing are recommended.', spermCountLabel: 'Sperm count', whoPass: 'Green: meets WHO standard', headBodyRatio: 'Morphology and head-body ratio', normalMorphology: 'Normal morphology', lowFollowUp: 'Low, follow-up recommended', motilityEstimateLabel: 'Motility estimate', progressive: 'Progressive', moderateMotility: 'Moderate motility', imageYolo: 'Image and YOLO annotation', originalImage: 'Original microscope image', yoloView: 'AI YOLO annotation view', detected: 'Detected', precision: 'Precision', confidence: 'Confidence', testSummary: 'Test summary', medicalBenefit: 'Clinical benefit', benefitText: 'This analysis took 1.2 seconds, reducing manual counting time and interpretation variation for laboratory staff.', testInfo: 'Test information', patientCode: 'Patient code', testItems: 'Test items', collectionTime: 'Collection time', saveToHistory: 'Save to patient history', historyList: 'Test history', historySearchPlaceholder: 'Search patient / sample ID / date / status', noRecords: 'No matching records', viewDetails: 'View details', previousPage: 'Back', patientData: 'Patient data', patientNumber: 'Patient number', sex: 'Sex', age: 'Age', phone: 'Phone', doctor: 'Doctor', processingStatus: 'Processing status', aiInterpretation: 'AI interpretation', processingTime: 'Processing time', notes: 'Medical notes', trend: 'Sperm count trend', loadingTitle: 'AI cloud analysis in progress', loadingDescription: 'Uploading image • YOLO detection • Morphology assessment',
    patientName: 'Patient name', patientId: 'Patient ID', patientCount: 'patients', recordCount: 'records', latestRecord: 'Latest test', viewPatientHistory: 'View patient history', patientHistory: 'Patient history', patientRecords: 'Test history', trendChartTitle: 'Historical trend', trendChartDescription: 'Compare analysis values across test dates for this patient.', trendMetric: 'Metric', trendDate: 'Test date', trendValue: 'Value',
    templateA: 'Sample A - High concentration', templateB: 'Sample B - Abnormal morphology', templateC: 'Sample C - Low concentration',
    loginEyebrow: 'Secure sign in', loginTitle: 'Sign in', loginDescription: 'Enter your username and password to use the Sperm AI analysis platform.', username: 'Username', password: 'Password', usernamePlaceholder: 'Enter username', passwordPlaceholder: 'Enter password', invalidCredentials: 'Incorrect username or password. Please try again.', login: 'Sign in', logout: 'Sign out',
    filter: 'Filters', startDate: 'Start date', endDate: 'End date', clearFilters: 'Clear filters', resultCount: 'records', averageResults: 'Historical averages', averageConcentration: 'Average concentration', averageMotility: 'Average motility', averageMorphology: 'Average normal morphology', doctorComment: 'Doctor comment', doctorCommentPlaceholder: 'Enter a doctor comment or follow-up recommendation', saveComment: 'Save comment', commentSaved: 'Comment saved', expandRecord: 'Expand test details', collapseRecord: 'Collapse test details',
  },
  ko: {
    platform: '정자 AI 보조 분석 플랫폼',
    navigation: '빠른 탐색',
    home: '홈',
    analysis: '분석',
    history: '기록',
    settings: '설정',
    openMenu: '탐색 메뉴 열기',
    closeMenu: '탐색 메뉴 닫기',
    mainNavigation: '주요 탐색', systemStatus: '시스템 상태', normal: '정상', cloudModel: '클라우드 YOLO 모델', offlineReady: '오프라인 백업: 준비됨',
    settingsEyebrow: '환경 설정',
    settingsTitle: '시스템 설정',
    languageTitle: '언어 설정',
    languageDescription: '사용할 인터페이스 언어를 선택하세요. 이 설정은 기기에 저장됩니다.',
    saved: '저장됨',
    healthCardTitle: '건강보험 카드 리더 서비스',
    healthCardStatusReady: '정상',
    healthCardDescription: '컴퓨터에서 카드 리더를 사용하기 전에 로컬 리더 서비스를 설치하고 실행하세요. iPad와 휴대폰에서는 수동 입력을 사용하세요.',
    healthCardComputerOnly: '컴퓨터 전용',
    healthCardVersionLabel: 'v0.3.0',
    healthCardSupportedVersion: '지원 버전',
    healthCardLocalAddress: '로컬 서비스 주소',
    healthCardCurrentOrigin: '현재 웹사이트 Origin',
    healthCardPlatformLabel: '플랫폼 안내',
    healthCardPlatformMacos: 'macOS',
    healthCardPlatformWindows: 'Windows',
    healthCardPlatformMobile: 'iPad / 모바일',
    healthCardMacTitle: 'macOS 안내 (소스에서 빌드)',
    healthCardMacPrerequisites: 'macOS, 인터넷, Git, Rust/Cargo, PC/SC 호환 리더 및 드라이버가 필요합니다.',
    healthCardMacStepOne: '1단계: Rust 확인',
    healthCardMacStepOneHint: 'cargo가 없으면 Rust를 설치한 후 터미널을 다시 여세요.',
    healthCardMacStepTwo: '2단계: v0.3.0 다운로드',
    healthCardMacStepTwoHint: '기존 폴더가 있으면 해당 폴더로 이동해 v0.3.0을 checkout하세요.',
    healthCardMacStepThree: '3단계: 빌드',
    healthCardMacStepThreeHint: '처음에는 의존성을 다운로드합니다.',
    healthCardMacStepFour: '4단계: 서비스 시작',
    healthCardMacStepFourHint: '터미널을 열어 두세요. 닫거나 Control + C를 누르면 서비스가 중지됩니다.',
    healthCardVerifyVersion: '/version 확인',
    healthCardVerifySnapshot: '/ 카드 상태 확인',
    healthCardTroubleshooting: 'macOS 문제 해결',
    healthCardTroubleshootingItems: [{ title: 'cargo 없음: ', text: 'Rust 설치 후 터미널을 다시 여세요.' }, { title: '폴더가 이미 존재: ', text: '기존 폴더로 이동해 v0.3.0을 checkout하세요.' }, { title: '웹사이트 연결 실패: ', text: '생성된 --allow-origin 명령으로 다시 시작하세요.' }, { title: 'pcsc_unavailable: ', text: '리더 드라이버와 USB 연결을 확인하세요.' }, { title: 'SharingViolation: ', text: '다른 카드 프로그램을 닫으세요.' }, { title: '브라우저별 결과 차이: ', text: '각 브라우저의 로컬 네트워크 권한을 확인하세요.' }],
    healthCardWindowsTitle: 'Windows 안내 (v0.3.0 x64)',
    healthCardWindowsStepOne: '스마트 카드 리더 드라이버를 설치하세요.',
    healthCardWindowsStepTwo: '공식 v0.3.0 x64 리더를 다운로드하세요.',
    healthCardWindowsStepThree: '.exe를 더블 클릭하세요.',
    healthCardWindowsStepFour: '리더 창을 열어 두세요.',
    healthCardWindowsStepFive: '리더를 연결하고 건강보험 카드를 넣으세요.',
    healthCardWindowsStepSix: '설정으로 돌아와 리더 서비스 확인을 누르세요.',
    healthCardWindowsWarning: '리더 프로그램 창을 닫으면 카드 읽기가 중지됩니다.',
    healthCardWindowsNote: '현재는 테스트/초기 사용 방식이며 완전한 Windows 설치 프로그램이 아닙니다.',
    healthCardMobileTitle: 'iPad, iPhone 및 모바일 기기',
    healthCardMobileDescription: '현재 모바일 기기에서는 데스크톱 리더 서비스를 실행할 수 없습니다. 환자 정보를 수동 입력하세요.',
    healthCardManualInput: '수동 입력 사용',
    healthCardCopy: '명령 복사',
    healthCardCopied: '복사됨',
    healthCardStatusChecking: '확인 중…',
    healthCardStatusNotChecked: '확인하지 않음',
    healthCardStatusConnection: '로컬 리더 서비스에 연결할 수 없습니다.',
    healthCardStatusOldVersion: '이전 버전입니다. 리더를 업데이트하세요.',
    healthCardStatusPcscUnavailable: '스마트 카드 서비스를 사용할 수 없습니다.',
    healthCardStatusNoReader: '리더를 찾을 수 없습니다.',
    healthCardStatusEmpty: '리더가 연결되었습니다. 카드를 넣으세요.',
    healthCardStatusCardReady: '건강보험 카드를 읽었습니다.',
    healthCardStatusUnsupported: '건강보험 카드가 아닙니다.',
    healthCardStatusSharingViolation: '다른 프로그램이 카드를 사용 중입니다.',
    healthCardStatusNoCard: '건강보험 카드가 없습니다.',
    healthCardStatusUnavailable: '준비되지 않음',
    healthCardPrivacy: '개인정보 보호: 건강보험 카드 정보가 포함됩니다. 전체 결과나 개인정보를 공유하지 마세요.',
    healthCardService: '리더 서비스', healthCardPcscLabel: '컴퓨터 스마트 카드 서비스', healthCardRecheck: '다시 확인', healthCardStatusUnknown: '상태 알 수 없음', healthCardStatusReaderConnected: '연결됨', healthCardStatusReaderError: '리더 오류', healthCardCopyError: '복사할 수 없습니다. 명령을 직접 선택하세요.', healthCardCommandLabel: '명령', healthCardRustInstallLabel: 'Rust 설치 명령', healthCardDownloadLabel: 'v0.3.0 다운로드', healthCardExistingFolderLabel: '폴더가 이미 있는 경우', healthCardBuildLabel: '빌드 명령', healthCardLocalLabel: '로컬 개발 테스트', healthCardPreviewLabel: '현재 프리뷰 환경', healthCardProductionLabel: '공식 웹사이트 사용', healthCardAdvanced: '고급 정보 및 문제 해결',
    healthCardDownload: 'TW NHI IC Card Service 다운로드',
    healthCardDownloadDescription: '공식 v0.3.0 Releases 및 플랫폼별 다운로드 열기',
    healthCardWindowsDownload: 'Windows 64비트 리더 다운로드',
    healthCardWindowsDownloadDescription: '공식 v0.3.0 x64 .exe; 현재 설치 프로그램 불필요',
    healthCardStepsTitle: '다른 컴퓨터에서 설치한 후 사용하기',
    healthCardStepOne: '카드 리더 드라이버를 설치하고 리더를 컴퓨터에 연결하세요.',
    healthCardStepTwo: 'macOS에서는 v0.3.0 소스 코드를 빌드하고, Windows에서는 공식 v0.3.0 x64 실행 파일을 다운로드하세요.',
    healthCardStepThree: '건강보험 카드를 넣고 터미널 또는 명령 프롬프트를 여세요.',
    healthCardStepFour: '아래 운영체제에 맞는 리더 서비스를 실행하고 해당 창을 계속 열어 두세요.',
    healthCardStepFive: '이 웹사이트로 돌아와 로그인한 후 새 검사에서 건강보험 카드 읽기를 선택하세요.',
    healthCardStartCommand: '운영체제별 시작 (v0.3.0)',
    healthCardMac: 'macOS: 빌드 후 터미널에서 시작',
    healthCardWindows: 'Windows 64비트: 다운로드 후 더블 클릭',
    healthCardLinux: 'Linux x86_64: 다운로드 후',
    healthCardNote: '서비스는 http://127.0.0.1:12345를 사용합니다. Windows 리더 창을 닫으면 카드 읽기가 중지됩니다. 설치 프로그램, 자동 시작, 서명 및 고정 allow-origin은 향후 제품 개선 사항입니다.',
    healthCardCheckTitle: '리더 서비스 확인',
    healthCardCheckDescription: '/version, PC/SC, 리더 및 건강보험 카드를 순서대로 확인합니다.',
    healthCardBrowserNote: 'Google Chrome 사용을 권장합니다. 공식 웹사이트에서 처음 카드 읽기를 사용할 때 브라우저의 로컬 네트워크 접근을 허용하세요. 거부한 경우 Chrome 설정 → 로컬 네트워크 접근을 허용으로 변경하고 페이지를 새로 고친 후 다시 확인하세요. Safari는 브라우저 보안 제한이 있을 수 있으므로 연결되지 않으면 Chrome 또는 수동 입력을 사용하세요.',
    healthCardCheckButton: '리더 서비스 확인',
    healthCardChecking: '확인 중…',
    healthCardVersion: '서비스 버전',
    healthCardPcsc: 'PC/SC',
    healthCardReader: '리더',
    healthCardCard: '건강보험 카드',
    healthCardReady: '정상',
    healthCardUnavailable: '준비되지 않음',
    healthCardMacCommandTitle: 'macOS 개발 시작 (공식 웹사이트 출처)',
    dashboardEyebrow: '검사 작업대', dashboardTitle: '정자 검사 시스템', newAnalysis: '새 검사', pendingSamples: '처리 대기 검체', todayWork: '오늘의 작업', sampleId: '검체 번호', receivedAt: '접수 시간', status: '상태', action: '작업', recentTests: '최근 검사', thisWeek: '이번 주', concentration: '농도', motility: '운동성', morphology: '형태', interpretation: '판독', view: '보기', pending: '대기', analyzing: '진행 중', attention: '주의 필요', completed: '완료', todayPending: '오늘 처리 대기', cloudAnalyzing: '클라우드 분석 중', manualReview: '수동 확인 대기', todayClosed: '오늘 완료', startAnalysis: '분석 시작', reviewResult: '결과 검토', followUp: '추적 관찰', uploadSettings: '검사 설정', newTest: '새 검사', basicInfo: '검체 기본 정보', patientSampleId: '환자 / 검체 번호', spermCount: '정자 수와 농도 (YOLO 계수)', required: '필수', morphologyAssessment: '형태 및 머리-몸통 평가', motilityEstimate: '운동성 예측', toggleMotility: '운동성 분석 전환', imageSource: '이미지 출처', cloudTemplate: '옵션 A: 클라우드 템플릿', cameraUpload: '옵션 B: 카메라 / 앨범 업로드', chooseImage: '이미지 선택', openCamera: '카메라를 열거나 앨범에서 이미지 선택', videoExtract: '옵션 C: 짧은 영상 추출', videoMode: '영상 프레임 분석 모드 (준비 중)', uploadVideo: '1초 영상 업로드', startCloudAnalysis: 'AI 클라우드 분석 시작', analysisResult: 'AI 분석 결과', reanalyze: '다시 분석', retest: '재검사', downloadPdf: 'PDF 다운로드', downloadReport: '보고서 다운로드', aiResult: 'AI 판독 결과', resultSummary: '분석 결과 정자 농도가 낮습니다. 전문가 확인과 후속 검사를 권장합니다.', spermCountLabel: '정자 수', whoPass: '녹색: WHO 기준 충족', headBodyRatio: '형태 및 머리-몸통 비율', normalMorphology: '정상 형태', lowFollowUp: '낮음, 추적 관찰 권장', motilityEstimateLabel: '운동성 예측', progressive: '전진성', moderateMotility: '운동성 보통', imageYolo: '이미지 및 YOLO 표시', originalImage: '원본 현미경 이미지', yoloView: 'AI YOLO 표시 보기', detected: '검출 성공', precision: 'Precision', confidence: 'Confidence', testSummary: '검사 요약', medicalBenefit: '임상 효과', benefitText: '분석에 1.2초가 걸려 검사자의 수동 계수 시간과 판독 편차를 줄였습니다.', testInfo: '검사 정보', patientCode: '환자 코드', testItems: '검사 항목', collectionTime: '채취 시간', saveToHistory: '환자 기록에 저장', historyList: '검사 기록 목록', historySearchPlaceholder: '환자 / 검체 번호 / 날짜 / 상태 검색', noRecords: '조건에 맞는 기록이 없습니다', viewDetails: '상세 보기', previousPage: '이전 페이지', patientData: '환자 정보', patientNumber: '환자 번호', sex: '성별', age: '나이', phone: '전화', doctor: '담당 의사', processingStatus: '처리 상태', aiInterpretation: 'AI 판독 정보', processingTime: '처리 시간', notes: '진료 기록 및 메모', trend: '정자 수 추이', loadingTitle: 'AI 클라우드 분석 중', loadingDescription: '이미지 업로드 • YOLO 검출 • 형태 평가',
    patientName: '환자 이름', patientId: '환자 ID', patientCount: '명', recordCount: '건 검사', latestRecord: '최근 검사', viewPatientHistory: '환자 기록 보기', patientHistory: '환자 기록', patientRecords: '검사 기록', trendChartTitle: '과거 추이', trendChartDescription: '이 환자의 검사 날짜별 분석 수치 변화를 비교합니다.', trendMetric: '비교 지표', trendDate: '검사 날짜', trendValue: '수치',
    templateA: '샘플 A - 고농도 정상', templateB: '샘플 B - 형태 이상 사례', templateC: '샘플 C - 저농도 추적 관찰',
    loginEyebrow: '보안 로그인', loginTitle: '로그인', loginDescription: '정자 AI 검사 플랫폼을 사용하려면 아이디와 비밀번호를 입력하세요.', username: '아이디', password: '비밀번호', usernamePlaceholder: '아이디 입력', passwordPlaceholder: '비밀번호 입력', invalidCredentials: '아이디 또는 비밀번호가 올바르지 않습니다. 다시 시도하세요.', login: '로그인', logout: '로그아웃',
    filter: '필터', startDate: '시작 날짜', endDate: '종료 날짜', clearFilters: '필터 지우기', resultCount: '개 기록', averageResults: '검사 평균 결과', averageConcentration: '평균 농도', averageMotility: '평균 운동성', averageMorphology: '평균 정상 형태', doctorComment: '의사 소견', doctorCommentPlaceholder: '의사 소견 또는 추적 관찰 권고를 입력하세요', saveComment: '소견 저장', commentSaved: '소견이 저장됨', expandRecord: '검사 상세 펼치기', collapseRecord: '검사 상세 접기',
  },
}

export const LanguageContext = createContext(null)

export function useLanguage() {
  return useContext(LanguageContext)
}

export const languageOptions = [
  { value: 'zh', label: '繁體中文' },
  { value: 'en', label: 'English' },
  { value: 'ko', label: '한국어' },
]
